on:
  push:
    branches-ignore:
      - master

permissions:
  contents: read

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup PHP Environment
        uses: nanasess/setup-php@v4
        with:
          php-version: '8.3'

      # PHP Composer
      - name: Validate composer.json and composer.lock
        run: composer validate --strict
      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v3
        with:
            path: vendor
            key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
            restore-keys: |
              ${{ runner.os }}-php-
      - name: Install dependencies
        run: composer install --prefer-dist --no-progress
